### PR TITLE
update spec for version 0.6.0

### PR DESCRIPTION
**Pull request by surajssd**

### CODE REVIEW

**Comment by surajssd** [comment]
ping @praveenkumar

**Review by praveenkumar — COMMENTED** [review]
Since we already have package in place can we also do a scratch build with this change and run rpmlint?

**Comment by surajssd** [comment]
@praveenkumar what exactly needs to be done?

**Comment by praveenkumar** [comment]
LGTM 👍 , checked rpmlint and no error.

**Comment by surajssd** [comment]
@dustymabe can you give me admin access on this repo so that i can merge these PRs?

**Comment by praveenkumar** [comment]
@surajssd you can only have admin access to dist-git once you are proven packager.

**Comment by surajssd** [comment]
>@surajssd you can only have admin access to dist-git once you are proven packager.

Even for this github repo I need to be a proven packager? How is that?

**Comment by praveenkumar** [comment]
> Even for this github repo I need to be a proven packager? How is that?

Ah, I misunderstood your request. No you don't need any proven packager for github repo admin :)

**Comment by dustymabe** [comment]
so this repo really has no relation to the actual repo that is used to build the package. It's just another remote that I configured so that we can sync. I'll give you access to this repo, but really it's just useful for "reviews".

**Comment by surajssd** [comment]
@dustymabe thanks a lot :+1:

**Comment by surajssd** [comment]
@praveenkumar thanks for LGTM merged!

**Comment by dustymabe** [comment]
@surajssd what you should really do is not actually push the merge button for this PR using the github UI. -- basically this repo should be a 'read-only' version of the repo.

1. open up PR here
2. go through review with praveen
3. praveen LGTM and then he merges things into the dist-git kompose repo
4. praveen pushes current master of dist-git to this repo

after praveen pushes current master of the dist-git repo here then this PR will automatically be marked as "merged". github will recognize that the commit in the PR is now in master and represent it the right way :)

**Comment by surajssd** [comment]
oops my bad :(

got the process, I didn't realize that before, so much to learn in this! But yes this makes sense!

One more noob question, how do I revert it now?

**Comment by dustymabe** [comment]
dont worry about it, just have praveen force push to master when he gets ready to do so

**Pull request merged**
