### PR TITLE
New release for 0.3.0 version of kompose

### PR DESCRIPTION
**Pull request by surajssd**
Changes to `parsedeps.go`:
kompose moved from godeps to glide so now we there is no
godeps.json but it's glide.lock file which needs to be parsed

### CODE REVIEW

**Comment by surajssd** [comment]
TODO:

- [x] Add git as dependecy (This is needed because when using buildconfig with openshift)

**Comment by surajssd** [comment]
@dustymabe also added the test flags!

**Comment by surajssd** [comment]
@dustymabe one question: for doing `kompose up` we need that user has config in `~/.kube/config` so does komopose should do anything for that?

**Comment by dustymabe** [comment]
> @dustymabe one question: for doing kompose up we need that user has config in ~/.kube/config so does komopose should do anything for that?

I don't think the rpm should do anything for that on install because new users can get created on the system after kompose gets installed. if kompose has logic to create this file on startup then I would do that. If kompose is still relying on kubectl to have created this file or for the user to create the file manually then I wouldn't worry about doing this in kompose.

**Comment by surajssd** [comment]
Yes kompose relies on kubectl to create it

**Comment by surajssd** [comment]
@dustymabe what do you think about the rest?

**Comment by dustymabe** [comment]
@surajssd going through the rest today.

**Comment by dustymabe** [comment]
@surajssd all of this has been merged upstream

**Pull request merged**
